language: node_js
node_js:
  - 12

env:
  - DATABASE_URL=postgresql://'postgres@localhost:5432/topups_db'

before_script:
  - psql -c 'create database topups_db;' -U postgres
  - psql -c "create user coder WITH PASSWORD 'pg123';" -U postgres

services:
  - postgresql
